/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DecentralizedNovelChapter } from "./DecentralizedNovelChapter";
export type { DecentralizedNovelVoteToken } from "./DecentralizedNovelVoteToken";
export type { NovelManagement } from "./NovelManagement";
