/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NovelManagement } from "./NovelManagement";
export * as factories from "./factories";
export { NovelManagement__factory } from "./factories/NovelManagement__factory";
