/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DecentralizedNovelChapter__factory } from "./DecentralizedNovelChapter__factory";
export { DecentralizedNovelVoteToken__factory } from "./DecentralizedNovelVoteToken__factory";
export { NovelManagement__factory } from "./NovelManagement__factory";
